### ISSUE TITLE
Unable to deploy Director

### ISSUE THREAD

**Issue by mcowger** [making/terraforming-pks-gcp#1]
Hi,

I followed the full procedure listed, and my plan executed successfully.  However after configuring OpsMan and attempting to deploy the Director, its unable to connect to bosh/0 with a timeout.  Is there a missing firewall rule somewhere?

**Comment by making** [comment]
I've never met a timeout to director.
If you prepared the GCP environment with this terraform template, firewall rule should be fine.

Which version of OpsManager are you using?
v2.1-build.304 works for me.

**Comment by mcowger** [comment]
pcf-gcp-2.1-build.314.tar.gz here.  I could fall back to 304 and give it a shot.

**Comment by making** [comment]
sounds weird. 314 should also work.

**Comment by making** [comment]
I'm not sure if you are using my concourse pipeline.
https://github.com/making/terraforming-pks-gcp/blob/master/ci/pipeline.yml#L198-L313

If you configured the director via opsman's web ui, I can't see whether your configurations are correct.

**Comment by mcowger** [comment]
I’m not using the concourse method - but I’ll give that a try to see if I missed something in the UI level.

**Comment by mcowger** [comment]
I figured out whats missing...by default the tag that OpsMan gives the director is pcf-vms, which isn't in the network firewall tags.
